version: '3.8'

services:

  db:
    container_name: postgres
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    networks:
      - app_net
    volumes:
      - app_volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d users"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot
    environment:
      host: postgres
      user: root
      password: admin
      db: users
      port: 5432
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy

networks:
  app_net:
    name: app_net

volumes:
  app_volume:
    name: app_volume
